services:
  - type: web
    name: chatz-artwork
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
    healthCheckPath: /
    autoDeploy: true
    branch: main
    rootDir: .
